# Generated by Django 5.2.7 on 2025-12-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_car_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('economy', 'Економ'), ('comfort', 'Комфорт'), ('business', 'Бізнес'), ('suv', 'SUV'), ('premium', 'Преміум')], default='economy', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Електро'), ('hybrid', 'Гібрид')], default='gasoline', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Автомат'), ('manual', 'Механіка')], default='automatic', max_length=20),
        ),
    ]
